travis:
  secure:
    BINSTAR_TOKEN: LKA30pD70Pa3ULE2ulpg/0N6LxRyTQn7M2u0pysSip/IQHx7YIpncNg1Ewt+Kb/i6oemmMmx7wndAI+HuY7rr41Sd6XWM36Rw/rbgoMg1avAljwHdUlhN+Ho8pKKpg/PWJGtTRBIyCllqSPHcFiVOjSyFycBvY6gub7jFtgB3Z6R1zMU3DZJJgw+ja4P7x0q8qOQ2+Ib7evonLcj/z9/OIevSZKP5CQ0xIwg4O2B6SFysvn9t8BLtYj1p+Lx1ch542Cksnd/HJoIn5WtRZMhI2leayPJGT/GYZKchy+oZBl7Y9ieyzOuJt1qFFOqfAm0WDvlC6WODWPixh2kiq3eMqlSktepRmFY4asrpUbhcfd2vrm4HxtIFOR3Xn3PUDojPvlb5pOkZ5ckq9Mq4RGrDDWCHPG8vJOjELWd0RJ8f06LDFq9T0Ft9LPM6tRUD5J2HnM4n6YBIwFphrOy7HdjTyBAHg0ItMfKzDEXW4Ffs+dfwoOQAXDiowVuApZ/ABg8p7RHGnAQes7DL0fT/W2j1tvv34CR1aSnZ2WUs7ul6WYTz/xuIBcna92Ks3lwwoI9PCt3iwbLwF80pZZKIJ90OQWplsa3WQpYhOBfNaOWfTLW9HHXYU2tboJT3rJflt073kMgeGqx7zg9106aVBvfmlBiwGnUUlyKBETPzRfkJQU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
