travis:
  secure:
    BINSTAR_TOKEN: jUmmxqHT9bAmeYQy/hG3FiT6RocYF6l1SS8mrQ6JSaUZb8kig4V2wYvJCuns1aEWM6hS/43jo9NKa2ybybYJIvrVZ7O2cweZRzOwWX+wFGLZRBw4pF+46jmTlUvz95Gtvbi+Tpv4cteoBBjHTBv4ffJiBsLZ9PlD6fWr1MInjpuQ8/dcVCLQMCbqSNZytAheZTNnTl1mJoxE51fTYRCJCD4vUuWzyxT7rFPqmandDjgTrrRU9UVJZ+MBZR/cgje3LigRfJ9U1f7YMoNg2/6QQgyOWRB/hCCu/KJTtvtxyv4Jy5qS1LLzkRCM1NKeU47+FUl7uGo4kMph9zji/H6sWXc7AYHwjwxpAoGQrZxEKZxw8XipmMR3nOCamT8X3TOTL0fUeEgyThL4MN5Y+aEDBll3MiB5B4xgSKUxZ0Ewf1r94YSwhtXAsYrqYYKG2tvgsjBzeHPtbOGINEdZTZjzKxlJLN0eJhFUEuJ22rbn2mE7iSvmCUzDN3QpF98HoGnWd6xQYmz7CWSP+T8geGBE8xtLSLa4fCEzjrTIPJ/UTlzaTABybjG3KuTbOD5+WVI3PbusPDuddW7NQ6plT0Nb1UpY3vF0iGacsIkwkysIKhvJAImgOy2GZk2IYA63le6GBZBtac0Z8nA1hRTTnfk2eTUzeonlfIEehulonq0mXLI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
